# Generated by Django 5.1.3 on 2024-11-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Employees_id', models.CharField(max_length=20, primary_key='True', serialize=False)),
                ('Firstname', models.CharField(max_length=30, verbose_name='Firstname')),
                ('Lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('Surname', models.CharField(max_length=30, verbose_name='Surname')),
            ],
        ),
        migrations.CreateModel(
            name='User_Requests',
            fields=[
                ('Request_id', models.CharField(max_length=20, primary_key='True', serialize=False)),
                ('Them', models.CharField(max_length=30)),
                ('Requesttype', models.CharField(max_length=30)),
                ('Priority', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Responsibleemployee', models.CharField(max_length=30)),
                ('Employees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.employees')),
            ],
        ),
    ]
